#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Description: Check to verify OTRS 5 Summary Status
# Author: Phillipe Smith <phillipelnx@gmail.com>
#
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Output is taken from OTRS_HOME/otrs.Console.pl Maint::Daemon::Summary 
#<<<otrs_summary>>
#     CoreCacheCleanup                         2017-10-01 00:20:00  Success      < 1 Second         2017-10-08 00:20:00 
#     EscalationCheck                          2017-10-03 08:55:00  Success      4.0 Second(s)      2017-10-03 09:00:00 
#     GenerateDashboardStats                   2017-10-03 08:05:00  Success      < 1 Second         2017-10-03 09:05:00 
#     ITSMChangesCheck                         2017-10-03 08:50:00  Success      1.0 Second(s)      2017-10-03 09:00:00 
#     LoaderCacheDelete                        2017-10-01 00:30:00  Success      < 1 Second         2017-10-08 00:30:00 
#     MailAccountFetch                         2017-10-03 08:58:00  Success      1.0 Second(s)      2017-10-03 08:59:00 
#     RebuildEscalationIndex                   2017-10-03 08:56:00  Success      < 1 Second         2017-10-03 09:00:00 
#     RenewCustomerSMIMECertificates           2017-10-03 02:02:00  Success      < 1 Second         2017-10-04 02:02:00 
#     SessionDeleteExpired                     2017-10-03 08:55:00  Success      < 1 Second         2017-10-03 10:55:00 
#     SpoolMailsReprocess                      2017-10-03 00:10:00  Success      < 1 Second         2017-10-04 00:10:00 
#     TicketAcceleratorRebuild                 2017-10-03 01:01:00  Success      1.0 Second(s)      2017-10-04 01:01:00 
#     TicketPendingCheck                       2017-10-03 08:45:00  Success      1.0 Second(s)      2017-10-03 10:45:00 
#     TicketUnlockTimeout                      2017-10-03 08:35:00  Success      < 1 Second         2017-10-03 09:35:00 
#     SurveyRequestsSend                       2017-10-03 08:40:00  Fail         < 1 Second         2017-10-03 09:00:00 

def inventory_otrs_tasks_summary(info):
    if len(info) > 0 and ('Success' in info[0] or 'Fail' in info[0]):
        return [(None, {})]

def check_otrs_tasks_summary(item, params, info):
    status      = 0
    output      = []
    long_output = []
    perfdata    = []

    for value in info:
        last_execution = ' '.join(value[1:3])
        last_duration  = ' '.join(value[4:7]) if len(value) == 9 else ' '.join(value[4:6])
        next_execution = ' '.join(value[-2:])
        last_status    = value[3]
        taskname       = value[0] if last_status == 'Success' else value[0]+'(!!)'
        textinfo       = '%s (last execution: %s, last status: %s, last duration: %s, next execution: %s)' % (taskname, last_execution, last_status, last_duration, next_execution) 

        if value[0] in params.keys() and params[value[0]]:
            last_status = params[value[0]]

        if last_status == 'Fail':
            status = 2 
            output.append(textinfo)
        else:            
            long_output.append(textinfo)
    
    if status == 0:
        output = [ 'All tasks are successfully executed!' ]
    
    return (status, ', '.join(output) + '\n' + '\n\n'.join(long_output))

check_info['otrs_tasks_summary'] = {
    'inventory_function'     : inventory_otrs_tasks_summary,
    'check_function'         : check_otrs_tasks_summary,
    'service_description'    : 'OTRS Tasks Summary',
    'has_perfdata'           : False,
    'default_levels_variable': 'otrs_tasks_summary_default_levels'
}
